## ============================================================================
## SEMAPA - RabbitMQ config
## ============================================================================

management.load_definitions = /etc/rabbitmq/definitions.json

# Memoria
vm_memory_high_watermark.relative = 0.6

# Disco
disk_free_limit.relative = 2.0

# Logging
log.console = true
log.console.level = info
log.file = false

# Heartbeat
heartbeat = 60
